
import Entidades.Pergunta;
import Entidades.Resposta;
import Infra.TextFileManager;
import Repositorio.PerguntasDAO;
import Repositorio.RespostasDAO;
import java.io.IOException;
import java.net.URISyntaxException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Murilo
 */
public class ConfiguracaoProva extends javax.swing.JFrame {

    /**
     * Creates new form ConfiguracaoProva
     */
    public ConfiguracaoProva() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        rdbFacil = new javax.swing.JRadioButton();
        rdbMedio = new javax.swing.JRadioButton();
        rdbDificil = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        buttonGroup1.add(rdbFacil);
        rdbFacil.setText("Fácil");

        buttonGroup1.add(rdbMedio);
        rdbMedio.setText("Médio");

        buttonGroup1.add(rdbDificil);
        rdbDificil.setText("Difícil");

        jLabel1.setText("Selecione a dificuldade:");

        jButton1.setText("Gerar Prova");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rdbFacil)
                        .addGap(18, 18, 18)
                        .addComponent(rdbMedio)
                        .addGap(18, 18, 18)
                        .addComponent(rdbDificil)))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdbFacil)
                    .addComponent(rdbMedio)
                    .addComponent(rdbDificil))
                .addGap(26, 26, 26)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(139, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            TextFileManager textFileManager = new TextFileManager("Teste gerado");
            PerguntasDAO perguntasDao = new PerguntasDAO();
            RespostasDAO respostasDao = new RespostasDAO();
            String[] letras = {"a", "b", "c", "d", "e", "f", "g", "h"};
            int i = 0;

            int dificuldade;
            if (rdbFacil.isSelected()) {
                dificuldade = 0;
            } else if (rdbMedio.isSelected()) {
                dificuldade = 1;
            } else {
                dificuldade = 2;
            }


            ArrayList<Pergunta> perguntas = perguntasDao.RetornarPerguntas(dificuldade);

            textFileManager.EscreverNoArquivo("Nome do aluno:\n\r");
            textFileManager.AdicionarLinhasAoArquivo("Disciplina: \t\t Data:\n\r");
            for (Pergunta p : perguntas) {
                i = 0;
                textFileManager.AdicionarLinhasAoArquivo("\n\r" + p.Pergunta + "\n\r");
                ArrayList<Resposta> respostas = respostasDao.RetornarRepostas(p.Id);

                for (Resposta r : respostas) {
                    textFileManager.AdicionarLinhasAoArquivo("\tAlternativa " + letras[i++] + ") " + r.Resposta + "\n\r");
                }
            }

            if (JOptionPane.showConfirmDialog(this, "Deseja também gerar o gabarito?") == 0) {
                textFileManager = new TextFileManager("Gabarito gerado");
                textFileManager.EscreverNoArquivo("---------GABARITO--------\n\r\n\r");

                for (Pergunta p : perguntas) {
                    i = 0;
                    textFileManager.AdicionarLinhasAoArquivo("\n\r" + p.Pergunta + "\n\r");
                    ArrayList<Resposta> respostas = respostasDao.RetornarRepostas(p.Id);

                    for (Resposta r : respostas) {
                        if(r.EhCorreta)
                        textFileManager.AdicionarLinhasAoArquivo("\t(Esta é resposta correta)\n\r");
                            
                        textFileManager.AdicionarLinhasAoArquivo("\tAlternativa " + letras[i++] + ") " + r.Resposta + "\n\r");
                    }
                }

            }


            JOptionPane.showMessageDialog(this, "Prova gerada com sucesso!!!\n Verifique no diretória base do projeto.");

        } catch (URISyntaxException | IOException | SQLException | ClassNotFoundException | InstantiationException | IllegalAccessException ex) {
            Logger.getLogger(ConfiguracaoProva.class.getName()).log(Level.SEVERE, null, ex);

            JOptionPane.showMessageDialog(this, "Erro ao gerar prova!!!");

        }

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConfiguracaoProva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConfiguracaoProva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConfiguracaoProva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConfiguracaoProva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConfiguracaoProva().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton rdbDificil;
    private javax.swing.JRadioButton rdbFacil;
    private javax.swing.JRadioButton rdbMedio;
    // End of variables declaration//GEN-END:variables
}
